### ISSUE TITLE
BigDecimal.new is deprecated

### ISSUE THREAD

**Issue by drnic** [civo/cli-rubygem#51]
I installed civo_cli into MacOS/Ruby 2.6.4 and see a Ruby warning when I use the CLI:

```
$ rvm current
ruby-2.6.4
$ uname -a
Darwin starkair.lan 18.7.0 Darwin Kernel Version 18.7.0: Sat Oct 12 00:02:19 PDT 2019; root:xnu-4903.278.12~1/RELEASE_X86_64 x86_64
$ civo
/Users/drnic/.rvm/gems/ruby-2.6.4/gems/activesupport-4.2.11.1/lib/active_support/core_ext/object/duplicable.rb:111: warning: BigDecimal.new is deprecated; use BigDecimal() method instead.
```

**Comment by andyjeffries** [comment]
Hey @drnic, thanks for the bug report. We were using an unpinned version of ActiveSupport (because they all work with our REST client - [Flexirest](https://github.com/flexirest/flexirest)), but now I've pinned it in this app to ActiveSupport 6.0 or above (because apparently 4.2.11 as you have installed has a deprecation warning now). 

Pushed as Civo CLI v0.5.7 (remember to give rubygems the usual 5-10 minutes for it to clear from their cache and be installable).
